---
language: python
python:
  - 3.6
services: docker

env:
  matrix:
    - MOLECULE_DOCKER_IMAGE: debian:jessie
    - MOLECULE_DOCKER_IMAGE: debian:stretch
    - MOLECULE_DOCKER_IMAGE: ubuntu:xenial
    - MOLECULE_DOCKER_IMAGE: ubuntu:bionic
    - MOLECULE_DOCKER_IMAGE: centos:6
    - MOLECULE_DOCKER_IMAGE: centos:7

install:
  - pip install pipenv
  - pipenv install -d

script:
  - pipenv run molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
